/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cdiddy.gui.welcome;

import cdiddy.objects.Team;
import cdiddy.utils.application.TeamService;
import java.awt.Component;
import java.util.List;
import javax.swing.AbstractCellEditor;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author DMDD
 */
public class WelcomePanel extends javax.swing.JPanel {
private TeamService teamservice;
private  List<Team> listTeam;
private TeamTableModel teamModel = new TeamTableModel();
    /**
     * Creates new form WelcomePanel
     */
    public WelcomePanel() {
        initComponents();
    }
    public WelcomePanel(TeamService teamservice) 
    {
        initComponents();
        this.teamservice = teamservice;
         jComboBox1.removeAllItems();
         listTeam = this.teamservice.loadUserTeams();
         populateTeamTable();
       
         
    }
    public void loadTableForLeauge(String leaugeid)
    {
        listTeam = this.teamservice.loadLeaugeTeams(leaugeid);
        populateTeamTable();

    }
    private void populateTeamTable()
    {
        for(Team team : listTeam)
        {
            jComboBox1.addItem(team);
            teamModel.addRow(team);
        }
        jComboBox1.setSelectedIndex(0);
    }
    public class TeamCellEditorRenderer extends AbstractCellEditor implements TableCellRenderer, TableCellEditor 
    {
         private static final long serialVersionUID = 1L;
        private UserTeamPanel renderer = new UserTeamPanel();
        private UserTeamPanel editor = new UserTeamPanel();

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            renderer.setTeam((Team) value);
            return renderer;
        }

        @Override
        public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column) {
            editor.setTeam((Team) value);
            return editor;
        }

        @Override
        public Object getCellEditorValue() {
            return editor.getTeam();
        }

    }
    public class TeamTableModel extends DefaultTableModel {

    private static final long serialVersionUID = 1L;

    @Override
    public int getColumnCount() {
        return 1;
    }

    public void addRow(Team team) {
        super.addRow(new Object[]{team});
        //super.fireTableDataChanged();
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable(teamModel);

        jComboBox1.setMaximumRowCount(90);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTable1.setRowHeight(new UserTeamPanel().getPreferredSize().height);
        jTable1.setTableHeader(null);
        jScrollPane1.setViewportView(jTable1);
        TeamCellEditorRenderer teamCellEditorRenderer = new TeamCellEditorRenderer();
        jTable1.setDefaultRenderer(Object.class, teamCellEditorRenderer);

        jTable1.setDefaultEditor(Object.class, teamCellEditorRenderer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
