/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cdiddy.gui;

import cdiddy.objects.league.YahooLeague;
import cdiddy.utils.application.GameService;
import cdiddy.utils.system.ArrayConversionUtil;
import java.util.Arrays;
import java.util.Collection;
import java.util.LinkedList;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author cedric
 */
public class LeagueSettingsPanel extends javax.swing.JPanel {

    /**
     * Creates new form LeagueSettingsPanel
     */
    List<YahooLeague> watchedLeague;
    List<YahooLeague> unwatchedLeague;
    List<YahooLeague> databaseLeagues;
    DefaultListModel watchLeagueListModel ;
    DefaultListModel unWatchLeagueListModel;
    GameService gService;
    
    
    public LeagueSettingsPanel(GameService gService) 
    {
        this.gService = gService;
        unwatchedLeague = gService.getUserLeagues();
        watchedLeague = gService.getUserSavedLeagues();
        databaseLeagues = gService.getUserSavedLeagues();
        watchLeagueListModel = new DefaultListModel();
        unWatchLeagueListModel = new DefaultListModel();
        for(YahooLeague yl : unwatchedLeague)
        {
            if(watchedLeague.contains(yl))
            {
                unwatchedLeague.remove(yl);
            }
            else
            {
                unWatchLeagueListModel.addElement(yl);
            }
               
        }
        for(YahooLeague yl : watchedLeague)
        {
            watchLeagueListModel.addElement(yl);
        }
        initComponents();
    }
    
    private void transfer(List<YahooLeague> selectedLeagues, boolean isWatched)
    {
        List<YahooLeague> to;
        List<YahooLeague> from;
        if(isWatched)
        {
            to = watchedLeague;
            from = unwatchedLeague;
        }
        else
        {
            to = unwatchedLeague;
            from = watchedLeague;
        }
        
        for(YahooLeague yl : selectedLeagues)
        {
            from.remove(yl);
            to.add(yl);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        watchedList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        unWatchedList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addWatchedTeamButton = new javax.swing.JButton();
        removeWatchedTeamButton = new javax.swing.JButton();
        saveWatchedTeamButton = new javax.swing.JButton();

        watchedList.setModel(watchLeagueListModel);
        jScrollPane1.setViewportView(watchedList);

        unWatchedList.setModel(unWatchLeagueListModel);
        jScrollPane2.setViewportView(unWatchedList);

        jLabel1.setText("Teams");

        jLabel2.setText("UnWatched");

        jLabel3.setText("Watched");

        addWatchedTeamButton.setText(">>>");
        addWatchedTeamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addWatchedTeamButtonActionPerformed(evt);
            }
        });

        removeWatchedTeamButton.setText("<<<");
        removeWatchedTeamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeWatchedTeamButtonActionPerformed(evt);
            }
        });

        saveWatchedTeamButton.setText("Save");
        saveWatchedTeamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveWatchedTeamButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addWatchedTeamButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(removeWatchedTeamButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(76, 76, 76))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(saveWatchedTeamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(addWatchedTeamButton)
                        .addGap(48, 48, 48)
                        .addComponent(removeWatchedTeamButton)))
                .addGap(18, 18, 18)
                .addComponent(saveWatchedTeamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addWatchedTeamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addWatchedTeamButtonActionPerformed
    
        List<YahooLeague> transferList = new LinkedList<YahooLeague>();
        ArrayConversionUtil.fromArrayToCollection(unWatchedList.getSelectedValues(), transferList);
        
        transfer( transferList, true);
       
    }//GEN-LAST:event_addWatchedTeamButtonActionPerformed

    private void removeWatchedTeamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeWatchedTeamButtonActionPerformed
     
        List<YahooLeague> transferList = new LinkedList<YahooLeague>();
        ArrayConversionUtil.fromArrayToCollection(watchedList.getSelectedValues(), transferList);
        transfer( transferList, false);
    }//GEN-LAST:event_removeWatchedTeamButtonActionPerformed

    private void saveWatchedTeamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveWatchedTeamButtonActionPerformed
        YahooLeague[] selected = (YahooLeague [])watchedList.getSelectedValues();
        gService.removeUserSavedLeagues();
        gService.saveUserSavedLeagues(new LinkedList<YahooLeague>(Arrays.asList(selected)));
    }//GEN-LAST:event_saveWatchedTeamButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addWatchedTeamButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton removeWatchedTeamButton;
    private javax.swing.JButton saveWatchedTeamButton;
    private javax.swing.JList unWatchedList;
    private javax.swing.JList watchedList;
    // End of variables declaration//GEN-END:variables
}
