/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cdiddy.gui;

import cdiddy.utils.application.GameService;

/**
 *
 * @author cedric
 */
public class LeagueSettingsDialog extends javax.swing.JDialog {

    /**
     * Creates new form LeagueSettingsDialog
     */
    GameService gService; 
    public LeagueSettingsDialog(java.awt.Frame parent, boolean modal, GameService gService) {
        
        super(parent, modal);
        this.gService = gService;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new LeagueSettingsPanel(gService);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Leauge Settings");
        getContentPane().setLayout(new java.awt.FlowLayout());
        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
