/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cdiddy.gui;

import cdiddy.objects.Team;
import cdiddy.objects.comparators.TeamRankComparator;
import cdiddy.objects.league.YahooLeague;
import cdiddy.utils.application.GameService;
import cdiddy.utils.application.TeamService;
import java.awt.Component;
import java.util.Collections;
import java.util.List;
import javax.swing.AbstractCellEditor;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

/**
 *
 * @author cedric
 */
@Repository("leaugeTeamListPanel")
public class LeaugeTeamListPanel extends javax.swing.JPanel {
    @Autowired
    private TeamService teamService;
    @Autowired
    private GameService gameService;
    private  List<Team> listTeam;
    private TeamTableModel teamModel = new TeamTableModel();
    /**
     * Creates new form UserTeamListPanel
     */
    public LeaugeTeamListPanel() 
    {
        initComponents();
    
    }
    

    public void populateLeauge(String leagueID)
    {
        listTeam = teamService.loadLeaugeTeams(leagueID);
        Collections.sort(listTeam, new TeamRankComparator());
        teamModel = new TeamTableModel();
        jTable1.setModel(teamModel);
        populateTeamTable();
    }
    private void populateTeamTable()
    {
        if (listTeam != null)
        {    
            for(Team team : listTeam)
            {
                teamModel.addRow(team);
            }
        }
    }

    public void init() 
    {
            populateTeamTable();
         
        leaugeComboBox.removeAllItems();
        List<YahooLeague> userLeaguesList = gameService.getUserLeagues();
        for(YahooLeague leauge : userLeaguesList)
        {
            leaugeComboBox.addItem(leauge);
        }
        leaugeComboBox.setSelectedIndex(0);
         initComponents();
    }

    public class TeamCellEditorRenderer extends AbstractCellEditor implements TableCellRenderer, TableCellEditor 
    {
         private static final long serialVersionUID = 1L;
        private LeagueTeamPanel renderer = new LeagueTeamPanel();
        private LeagueTeamPanel editor = new LeagueTeamPanel();

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            renderer.setTeam((Team) value);
            return renderer;
        }

        @Override
        public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column) {
            editor.setTeam((Team) value);
            return editor;
        }

        @Override
        public Object getCellEditorValue() {
            return editor.getTeam();
        }

    }
    public class TeamTableModel extends DefaultTableModel 
    {
        private static final long serialVersionUID = 1L;

           @Override
           public int getColumnCount() {
               return 1;
           }

           public void addRow(Team team) {
               super.addRow(new Object[]{team});
               //super.fireTableDataChanged();
           }
       }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        leaugeComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 400));

        jTable1.setModel(teamModel);
        jTable1.setFillsViewportHeight(true);
        jScrollPane1.setViewportView(jTable1);
        jTable1.setRowHeight(new UserTeamPanel().getPreferredSize().height);
        jTable1.setTableHeader(null);
        TeamCellEditorRenderer teamCellEditorRenderer = new TeamCellEditorRenderer();
        jTable1.setDefaultRenderer(Object.class, teamCellEditorRenderer);
        jTable1.setDefaultEditor(Object.class, teamCellEditorRenderer);

        leaugeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Leauge :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(leaugeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(217, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leaugeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox leaugeComboBox;
    // End of variables declaration//GEN-END:variables
}
