/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cdiddy.gui;

import cdiddy.objects.SeasonStat;
import cdiddy.objects.Stat;
import cdiddy.objects.StatCategory;
import cdiddy.utils.application.StatsService;
import java.util.List;
import javax.swing.JComboBox;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author cedric
 */
public class SeasonComparePanel extends javax.swing.JPanel {

    /**
     * Creates new form SeasonComparePanel
     */
    
    
    StatsService statsService;
    JFreeChart chart;
    List<SeasonStat> listSS; 
    public SeasonComparePanel() {
        initComponents();
    }

    public SeasonComparePanel(StatsService statsService) 
    {
        
       
        this.statsService = statsService;
        
        initComponents();
    }
    public void init(List<SeasonStat> listSS)
    {
        this.listSS = listSS;
        jComboBox1.removeAllItems();
        if(listSS.size() > 0)
        {
            for(Stat stat : listSS.get(0).getStats())
            {
                StatCategory sc = statsService.getStatCategory(Integer.parseInt(stat.getStat_id()));
                jComboBox1.addItem(sc);
            }
            jComboBox1.setSelectedIndex(0);
            createBarChart(listSS, ((StatCategory)jComboBox1.getSelectedItem()).getStat_id());
        }
    }
    public void createBarChart(List<SeasonStat> listSS, int stat_id)
    {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        
        
         for(SeasonStat season : listSS)
         {
             for(Stat stat : season.getStats())
             {
               int tempStatID = Integer.parseInt(stat.getStat_id());
               if(tempStatID == stat_id)
               {    
                    StatCategory sc = statsService.getStatCategory(tempStatID);              
                    dataset.addValue(stat.getValue(), season.getSeason(), sc.getDisplay_name());
               }
             }
         
         }
         
            chart = ChartFactory.createBarChart(
                                                "Season Stats Comparison", // chart title
                                                "Category", // domain axis label
                                                "Value", // range axis label
                                                dataset, // data
                                                PlotOrientation.VERTICAL, // orientation
                                                true, // include legend
                                                true, // tooltips?
                                                false // URLs?
                                                );
            ((ChartPanel) jPanel1).setChart(chart);
            CategoryPlot plot = chart.getCategoryPlot();
            NumberAxis rangeAxis = (NumberAxis) plot.getRangeAxis();
            rangeAxis.setAutoRange(true);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new ChartPanel(chart, false);
        jComboBox1 = new javax.swing.JComboBox();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(164, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
       JComboBox cb = (JComboBox)evt.getSource();
       if(cb.getSelectedItem() != null)
       {
        createBarChart(listSS, ((StatCategory)cb.getSelectedItem()).getStat_id());
       }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
