/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cdiddy.gui;

import cdiddy.gui.UserTeamListPanel;
import cdiddy.objects.Team;
import cdiddy.objects.comparators.TeamRankComparator;
import cdiddy.utils.application.TeamService;
import java.awt.Component;
import java.util.Collections;
import java.util.List;
import javax.swing.AbstractCellEditor;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author DMDD
 */
public class WelcomePanel extends javax.swing.JPanel {
private TeamService teamservice;

    /**
     * Creates new form WelcomePanel
     */
    public WelcomePanel() {
        initComponents();
    }
    public WelcomePanel(TeamService teamservice) 
    {
        this.teamservice = teamservice;   
        initComponents();
           
    }
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new UserTeamListPanel(teamservice);
        jPanel2 = new LeaugeTeamListPanel(teamservice);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));
        jTabbedPane1.addTab("My Teams", jPanel1);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));
        jTabbedPane1.addTab("League", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    public void loadTableForLeauge(String leaugeid) {
       ((LeaugeTeamListPanel) jPanel2).populateLeauge(leaugeid);
       jTabbedPane1.setSelectedComponent(jPanel2); 
   }
}
